server:
  port: 8091
  tomcat:
    uri-encoding: UTF-8
spring:
  datasource:
      url: jdbc:mysql://106.14.39.22:3306/banma_all?useUnicode=true&characterEncoding=utf8&tinyInt1isBit=false&zeroDateTimeBehavior=convertToNull&useSSL=true
      username: root
      password: 123456
  application:
      name: authorization-server
#mybatis配置
mybatis:
  typeAliasesPackage: com.banmatrip.guardian.domain
  mapperLocations: classpath*:mapper/*/*.xml
  configuration.log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  configuration.call-setters-on-nulls: true

#登录页
sso:
  index:
    url: http://172.16.1.22:8091/home