server:
  port: 8091
  tomcat:
    uri-encoding: UTF-8
spring:
  datasource:
      url: jdbc:mysql://localhost:3306/banma_test_new?characterEncoding=utf8&allowMultiQueries=true
      username: root
      password: WgmvwSnq2ahUuoWS
  application:
      name: authorization-server
#mybatis配置
mybatis:
  typeAliasesPackage: com.banmatrip.guardian.domain
  mapperLocations: classpath*:mapper/*/*.xml
  configuration.log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  configuration.call-setters-on-nulls: true

#登录页
sso:
  index:
    url: http://localhost:8091/login