server:
  port: 8091
  tomcat:
    uri-encoding: UTF-8
spring:
  datasource:
      url: jdbc:mysql://172.16.1.18:3306/banma_dev?useUnicode=true&characterEncoding=utf8&tinyInt1isBit=false&zeroDateTimeBehavior=convertToNull&useSSL=true
      username: dev
      password: 123456
  application:
      name: authorization-server
#mybatis配置
mybatis:
  typeAliasesPackage: com.banmatrip.guardian.domain
  mapperLocations: classpath*:mapper/*/*.xml
  configuration.log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  configuration.call-setters-on-nulls: true

#登录页
sso:
  index:
    url: http://172.16.1.14:8091/home