server:
  port: 8081
  tomcat:
    uri-encoding: UTF-8

spring:
  datasource:
      url: jdbc:mysql://localhost:3306/banma_test_new?useUnicode=true&characterEncoding=utf8&tinyInt1isBit=false&zeroDateTimeBehavior=convertToNull&useSSL=true&allowMultiQueries=true
      username: root
      password: WgmvwSnq2ahUuoWS
      driver-class-name: com.mysql.jdbc.Driver
  application:
    name: report

#mybatis配置
mybatis:
  typeAliasesPackage: com.banmatrip.guardian.domain
  mapperLocations: classpath*:mapper/*/*.xml
  configuration.log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  configuration.call-setters-on-nulls: true

#oauth客户端配置
security:
  ignored: /favicon.ico,/scripts/**,/styles/**,/images/**
  sessions: always
  oauth2:
    sso:
      login-path: /login
    client:
      client-id: ssoclient
      client-secret: ssosecret
      access-token-uri: http://localhost:8091/oauth/token
      user-authorization-uri: http://localhost:8091/oauth/authorize
      client-authentication-scheme: form
    resource:
      jwt:
        key-uri: http://localhost:8091/oauth/token_key

#安全配置
securityconfig:
  logoutsuccssurl: /tosignout
  permitall: /rest/**
  deniedpage: /deny

zuul:
  routes:
    resource:
      path: /resource/**
      url: http://localhost:8092
      stripPrefix: true
      retryable:

#登出配置
sso:
  tosignout:
    url: http://localhost:8091/signout
