server:
  port: 8092
  tomcat:
    uri-encoding: UTF-8
# datasource
spring:
  datasource:
      url: jdbc:mysql://106.14.39.22:3306/banma_all?useUnicode=true&characterEncoding=utf8&tinyInt1isBit=false&zeroDateTimeBehavior=convertToNull&useSSL=true
      username: root
      password: 123456
  application:
      name: resource-service

#mybatis配置
mybatis:
  typeAliasesPackage: com.banmatrip.guardian.domain
  mapperLocations: classpath*:mapper/*/*.xml
  configuration.log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  configuration.call-setters-on-nulls: true

security:
  oauth2:
      resource:
        jwt:
          key-uri: http://172.16.1.22:8091/oauth/token_key


