server:
  port: 8107
  tomcat:
    uri-encoding: UTF-8
# datasource
spring:
  datasource:
    url: jdbc:mysql://rdsry5ng8fus2v021v53.mysql.rds.aliyuncs.com:3306/banma?useUnicode=true&characterEncoding=utf8&tinyInt1isBit=false&zeroDateTimeBehavior=convertToNull&useSSL=true
    username: banma
    password: banma123
    driver-class-name: com.mysql.jdbc.Driver
  application:
    name: resource-service

#mybatis配置
mybatis:
  typeAliasesPackage: com.banmatrip.guardian.domain
  mapperLocations: classpath*:mapper/*/*.xml
  configuration.log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  configuration.call-setters-on-nulls: true

security:
  oauth2:
      resource:
        jwt:
          key-uri: http://guardian.auth.bmtrip.com/oauth/token_key
