server:
  port: 8092
  tomcat:
    uri-encoding: UTF-8
# datasource
spring:
  datasource:
      url: jdbc:mysql://localhost:3306/banma_test_new?characterEncoding=utf8
      username: root
      password: WgmvwSnq2ahUuoWS
  application:
      name: resource-service

#mybatis配置
mybatis:
  typeAliasesPackage: com.banmatrip.guardian.domain
  mapperLocations: classpath*:mapper/*/*.xml
  configuration.log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  configuration.call-setters-on-nulls: true

security:
  oauth2:
      resource:
        jwt:
          key-uri: http://localhost:8091/oauth/token_key


